//LOGIN
export const ADD_LOGIN = "ADD_LOGIN";
export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const REMOVE_LOGIN = "REMOVE_LOGIN";

// Account Group actionTypes

export const ACCOUNT_GROUP_GET_DATA = "ACCOUNT_GROUP_GET_DATA";
export const ACCOUNT_GROUP_SET_DATA = "ACCOUNT_GROUP_SET_DATA";
export const ACCOUNT_GROUP_FAIL_DATA = "ACCOUNT_GROUP_FAIL_DATA";
export const DELETE_ACCOUNT_GROUP_FAIL = "DELETE_ACCOUNT_GROUP_FAIL";
export const POST_ACCOUNT_GROUP_DATA = "POST_ACCOUNT_GROUP_DATA";
export const POST_ACCOUNT_GROUP_DATA_START = "POST_ACCOUNT_GROUP_DATA_START";
export const POST_ACCOUNT_GROUP_DATA_FAIL = "POST_ACCOUNT_GROUP_DATA_FAIL";
export const EDIT_ACCOUNT_GROUP_ROW_START = "EDIT_ACCOUNT_GROUP_ROW_START";

export const FAIL_EDIT_ACCOUNT_GROUP = "FAIL_EDIT_ACCOUNT_GROUP";
export const CURRENT_USER_EDIT_ACCOUNT_GROUP =
  "CURRENT_USER_EDIT_ACCOUNT_GROUP";
export const UPDATE_ACCOUNT_GROUP_DATA_START =
  "UPDATE_ACCOUNT_GROUP_DATA_START";

// Questions actionTypes

export const QUESTIONS_GET_DATA = "QUESTIONS_GET_DATA";
export const QUESTIONS_SET_DATA = "QUESTIONS_SET_DATA";
export const QUESTIONS_FAIL_DATA = "QUESTIONS_FAIL_DATA";
export const DELETE_QUESTIONS_FAIL = "DELETE_QUESTIONS_FAIL";
export const POST_QUESTIONS_DATA = "POST_QUESTIONS_DATA";
export const POST_QUESTIONS_DATA_START = "POST_QUESTIONS_DATA_START";
export const POST_QUESTIONS_DATA_FAIL = "POST_QUESTIONS_DATA_FAIL";
export const EDIT_QUESTIONS_ROW_START = "EDIT_QUESTIONS_ROW_START";

export const FAIL_EDIT_QUESTIONS = "FAIL_EDIT_QUESTIONS";
export const CURRENT_USER_EDIT_QUESTIONS = "CURRENT_USER_EDIT_QUESTIONS";
export const UPDATE_QUESTIONS_DATA_START = "UPDATE_QUESTIONS_DATA_START";

// Users actionTypes

export const USERS_GET_DATA = "USERS_GET_DATA";
export const USERS_SET_DATA = "USERS_SET_DATA";
export const USERS_FAIL_DATA = "USERS_FAIL_DATA";
export const DELETE_USERS_FAIL = "DELETE_USERS_FAIL";
export const POST_USERS_DATA = "POST_USERS_DATA";
export const POST_USERS_DATA_START = "POST_USERS_DATA_START";
export const POST_USERS_DATA_FAIL = "POST_USERS_DATA_FAIL";
export const EDIT_USERS_ROW_START = "EDIT_USERS_ROW_START";

export const FAIL_EDIT_USERS = "FAIL_EDIT_USERS";
export const CURRENT_USER_EDIT_USERS = "CURRENT_USER_EDIT_USERS";
export const UPDATE_USERS_DATA_START = "UPDATE_USERS_DATA_START";

// Marking actionTypes

export const MARKINGS_GET_DATA = "MARKINGS_GET_DATA";
export const MARKINGS_SET_DATA = "MARKINGS_SET_DATA";
export const MARKINGS_FAIL_DATA = "MARKINGS_FAIL_DATA";
export const DELETE_MARKINGS_FAIL = "DELETE_MARKINGS_FAIL";
export const POST_MARKINGS_DATA = "POST_MARKINGS_DATA";
export const POST_MARKINGS_DATA_START = "POST_MARKINGS_DATA_START";
export const POST_MARKINGS_DATA_FAIL = "POST_MARKINGS_DATA_FAIL";
export const EDIT_MARKINGS_ROW_START = "EDIT_MARKINGS_ROW_START";

export const FAIL_EDIT_MARKINGS = "FAIL_EDIT_MARKINGS";
export const CURRENT_USER_EDIT_MARKINGS = "CURRENT_USER_EDIT_MARKINGS";
export const UPDATE_MARKINGS_DATA_START = "UPDATE_MARKINGS_DATA_START";

// Major Category actionTypes

export const MAJORCATS_GET_DATA = "MAJORCATS_GET_DATA";
export const MAJORCATS_SET_DATA = "MAJORCATS_SET_DATA";
export const MAJORCATS_FAIL_DATA = "MAJORCATS_FAIL_DATA";
export const DELETE_MAJORCATS_FAIL = "DELETE_MAJORCATS_FAIL";
export const POST_MAJORCATS_DATA = "POST_MAJORCATS_DATA";
export const POST_MAJORCATS_DATA_START = "POST_MAJORCATS_DATA_START";
export const POST_MAJORCATS_DATA_FAIL = "POST_MAJORCATS_DATA_FAIL";
export const EDIT_MAJORCATS_ROW_START = "EDIT_MAJORCATS_ROW_START";

export const FAIL_EDIT_MAJORCATS = "FAIL_EDIT_MAJORCATS";
export const CURRENT_USER_EDIT_MAJORCATS = "CURRENT_USER_EDIT_MAJORCATS";
export const UPDATE_MAJORCATS_DATA_START = "UPDATE_MAJORCATS_DATA_START";

// Sub Category actionTypes

export const SUBCATS_GET_DATA = "SUBCATS_GET_DATA";
export const SUBCATS_SET_DATA = "SUBCATS_SET_DATA";
export const SUBCATS_FAIL_DATA = "SUBCATS_FAIL_DATA";
export const DELETE_SUBCATS_FAIL = "DELETE_SUBCATS_FAIL";
export const POST_SUBCATS_DATA = "POST_SUBCATS_DATA";
export const POST_SUBCATS_DATA_START = "POST_SUBCATS_DATA_START";
export const POST_SUBCATS_DATA_FAIL = "POST_SUBCATS_DATA_FAIL";
export const EDIT_SUBCATS_ROW_START = "EDIT_SUBCATS_ROW_START";

export const FAIL_EDIT_SUBCATS = "FAIL_EDIT_SUBCATS";
export const CURRENT_USER_EDIT_SUBCATS = "CURRENT_USER_EDIT_SUBCATS";
export const UPDATE_SUBCATS_DATA_START = "UPDATE_SUBCATS_DATA_START";
